version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      # Install dependencies for CDK and other requirements
      - pip install --upgrade pip
      - python -m venv .venv
      - chmod +x .venv/bin/activate
      - .venv/bin/activate
      - pip install -r requirements.txt
      - echo $ENV_FILE | tr " " "\n" > parameters.yaml

  build:
    commands:
      # Run the build command for Python CDK
      - cdk synth SbiFptStack -c contxt=$CONTXT_ENV --require-approval never
      - cdk deploy SbiFptStack -c contxt=$CONTXT_ENV --require-approval never

      - cdk synth JavaStack -c contxt=$CONTXT_ENV --require-approval never
      - cdk deploy JavaStack -c contxt=$CONTXT_ENV --require-approval never

      - cdk synth PipelineJavaStack -c contxt=$CONTXT_ENV --require-approval never
      - cdk deploy PipelineJavaStack -c contxt=$CONTXT_ENV --require-approval never

      - cdk synth PipelineCDKStack -c contxt=$CONTXT_ENV --require-approval never
      - cdk deploy PipelineCDKStack -c contxt=$CONTXT_ENV --require-approval never

cache:
  paths:
    - '/root/.cache/pip/**/*'
